name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: m
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check flake
        run: nix flake check -v --show-trace --no-update-lock-file

  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12]
        package:
          - move-to-ts
          - move-cli
          - z3
          # Aptos
          - aptos
          - aptos-node
          - aptos-tools
          - aptos-full
          - move-cli-address32
          - move-ts-aptos
          # Sui
          - sui
          - sui-node
          - sui-gateway
          - sui-tools
          - sui-full
          - move-cli-address20
          - move-ts-sui
          # Envs
          - env-aptos-dev
          - env-move
          - env-rust
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: m
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --show-trace --print-build-logs .#${{ matrix.package }}
